branch-defaults:
  deployment:
    environment: transaction-broker-dev
environment-defaults:
  transaction-broker-dev:
    branch: null
    repository: null
global:
  application_name: datum-transaction-broker
  default_ec2_keyname: datum
  default_platform: arn:aws:elasticbeanstalk:ap-southeast-1::platform/Docker running
    on 64bit Amazon Linux/2.12.3
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
